# Generated by Django 6.0.6 on 2026-07-07 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qualifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_description', models.TextField()),
                ('url', models.URLField(unique=True)),
                ('company', models.CharField(max_length=50)),
                ('salary', models.IntegerField(default=-1)),
                ('scraped_at', models.DateField(auto_now_add=True)),
                ('qualifications', models.ManyToManyField(to='jobs.qualifications')),
                ('requirements', models.ManyToManyField(to='jobs.requirements')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.role')),
                ('tasks', models.ManyToManyField(to='jobs.tasks')),
            ],
        ),
    ]
